#!/bin/bash

#!/bin/bash

FILE=$1
FOLDERS=(classes conditional_statements data_types functions loops variables)


if [ -e "${FOLDERS[$2]}/$FILE.rb" ]; then
	echo "Already exists!"
else
cat >>${FOLDERS[$2]}/$FILE.rb<<EOF
# TITLE: $FILE
# DATE CREATED: $(date "+%Y-%m-%d %H:%M.%S")
# AUTHOR: jamari
EOF
fi